#!/usr/bin/env node
/**
 * Generates the Nostr keypairs for the CEO + 8 agents into `.env.buzz` (gitignored, chmod 600).
 * NEVER commit this file. See docs/keychain.md for the NIP-49 backup flow.
 */
import { writeFileSync, existsSync, chmodSync } from 'node:fs';
import { generateSecretKey, getPublicKey } from 'nostr-tools/pure';
import { bytesToHex } from '@noble/hashes/utils.js';
import { npubEncode, nsecEncode } from 'nostr-tools/nip19';

const ROLES = [
  'CEO',
  'agent-sales',
  'agent-souscription',
  'agent-sinistres',
  'agent-finance',
  'agent-conformite',
  'agent-hermes-orchestrator',
  'agent-ops',
  'agent-support',
] as const;

const OUT = new URL('../.env.buzz', import.meta.url);

if (existsSync(OUT)) {
  console.error(`[init-buzz-keys] ${OUT.pathname} already exists — delete it first to regenerate (keys are lost otherwise).`);
  process.exit(1);
}

const lines: string[] = ['# GENERATED BY scripts/init-buzz-keys.ts — DO NOT COMMIT (chmod 600)'];
const mapping: Record<string, { npub: string; nsec: string }> = {};

for (const role of ROLES) {
  const sk = generateSecretKey();
  const pkHex = getPublicKey(sk);
  lines.push(`${role.toUpperCase().replace(/-/g, '_')}_NSEC=${nsecEncode(sk)}`);
  lines.push(`${role.toUpperCase().replace(/-/g, '_')}_NPUB=${npubEncode(pkHex)}`);
  mapping[role] = { npub: npubEncode(pkHex), nsec: nsecEncode(sk) };
}

writeFileSync(OUT, lines.join('\n') + '\n', { mode: 0o600 });
try {
  chmodSync(OUT, 0o600);
} catch {
  // on Windows chmod is a best-effort no-op
}

console.log('[init-buzz-keys] npub mapping (to fill into BRIDGE_CEOPUBKEYS + RBAC):');
for (const [role, k] of Object.entries(mapping)) {
  console.log(`  ${role.padEnd(24)} ${k.npub}`);
}
console.log(`\n[init-buzz-keys] written ${OUT} (gitignored, mode 600). NEVER in git.`);
console.log('[init-buzz-keys] Backup: encrypt these nsec with NIP-49 (passphrase) — see docs/keychain.md');
